# Optimized for test database performance, not production.

listen_addresses = '*'
port = 8100
max_connections = 5000

shared_buffers = 256MB
work_mem = 16MB
maintenance_work_mem = 1024MB
max_parallel_maintenance_workers = 5
max_parallel_workers = 8

wal_level = minimal
fsync = off
synchronous_commit = off
full_page_writes = off
wal_compression = off
wal_init_zero = off
wal_recycle = off
checkpoint_timeout = 1d
archive_mode = off
max_wal_senders = 0

jit = off

log_min_duration_statement = -1
log_checkpoints = off
log_duration = off
log_statement = 'none'

track_activities = off
track_counts = off
track_io_timing = off
track_functions = none
track_commit_timestamp = off

autovacuum = off
log_autovacuum_min_duration = -1

max_locks_per_transaction = 1024
